services:
  mysql:
    image: mysql:8.4
    container_name: code-assessment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: tom@1121
      MYSQL_DATABASE: code_assessment
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
